[build]
  command = "echo 'Building Music Converter...'"
  publish = "."

[[redirects]]
  from = "/"
  to = "/converter.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/converter.html"
  status = 200

[[redirects]]
  from = "/convert"
  to = "/converter.html"
  status = 200

[[redirects]]
  from = "/index"
  to = "/index.html"
  status = 200
